version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - restore_cache:
                key: dependency-cache--{{ checksum "package-lock.json" }}
            - run: npm install
            - save_cache:
                key: dependency-cache--{{ checksum "package-lock.json" }}
                paths:
                  - ./node_modules
            - run: npm test
            - store_artifacts: 
                path: test-results.xml
                prefix: tests
            - store_artifacts:
                path: coverage
                prefix: coverage
            - store_test_results:
                path: test-results.xml
workflows:
    build-and-test:
      jobs:
        - build-and-test